### PR TITLE
Add snap installation instructions

### PR DESCRIPTION
**Pull request by flexiondotorg**
This pull request adds installation instructions for users of [snap enabled Linux distributions](https://snapcraft.io/docs/core/install). Snaps enable ISVs and projects to make their software available to millions of Linux users via the snap store and directly control delivery of software updates to their users. Snaps of stable desktop applications will also be available via the desktop Software Center, improving the discoverability of your software. Your software can be installed with a simple `snap install node-red --beta` simplifying the installation instructions for your users. Once the snap is released into the stable channel in the store, users no longer need to add the `--beta`.

### CODE REVIEW

**Comment by knolleary** [comment]
Hi, thanks for raising this.

Before we add anything about Snap, we need to understand it properly.

We're not going to put it at the very top of our instructions when it involves some packaging that we have no involvement.

**Comment by flexiondotorg** [comment]
@knolleary Node-RED is published by @dceejay

**Comment by knolleary** [comment]
ah ok - _that_ snap.

Not one we, as a project, have put much thought into as yet - certainly not the primary way we recommend of installing.

But certainly worth adding to the docs somewhere once we've put a bit more thought around it.

**Comment by flexiondotorg** [comment]
@knolleary @dceejay I'd certainly be very interested in helping progress the snap.

**Comment by dceejay** [comment]
Hi Martin  - yes happy to progress it - but been distracted with client work recently :-(... Any progress on getting the serial ports accessible to snap ?

**Comment by dceejay** [comment]
Manually edited so closing

**Pull request closed without merging**
