### PR TITLE
Deploying Node-RED on Azure Container Instances

### PR DESCRIPTION
**Pull request by manjularajamani**

### CODE REVIEW

**Comment by dceejay** [comment]
@manjularajamani - Hi are you able to accept the CLA with the correct email address as per links above ?

**Comment by manjularajamani** [comment]
Hi @dceejay,

Yes, I'm currently in the process of linking the correct email address with GitHub.

**Comment by manjularajamani** [comment]
Hi @dceejay 

I will create a new Pull Request for these changes.

**Pull request closed without merging**
