### PR TITLE
Fixing typo.

### PR DESCRIPTION
**Pull request by garnold**

### CODE REVIEW

**Comment by garnold** [comment]
@knolleary @dceejay (Bump)

**Comment by knolleary** [comment]
Hi, sorry for the delay.

As crazy as it may sound, as per our contribution guidelines, we need a signed contribution agreement before we can accept any commits into the repository - even for doc updates, even for trivial things like this.

Given the nature of the change, I'll treat this as a bug report rather than a pull request and apply the change myself.

Nick

**Comment by garnold** [comment]
@knolleary Makes sense (mostly ;) ).  I don't see any info on contribution guidelines in this repo... is a contribution agreement something I can enter as an individual contributor?

**Comment by dceejay** [comment]
Good point... ! now that's an issue to fix  :+1: 

(we kind of assume most people will come via the main node-red project - but hey... why should they... ?) - https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md

and yes most certainly you can - details in the CLA itself.

**Comment by garnold** [comment]
Perfect, thanks @dceejay !

**Pull request closed without merging**
